apiVersion: v1
kind: Service
metadata:
  labels:
    app: consumer-app
  name: consumer-app
spec:
  type: NodePort
  ports:
  - name: "consumer-app"
    port: 8080
    targetPort: 8080
    nodePort: 31001
  selector:
    app: consumer-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consumer-app
  name: consumer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-app
  template:
    metadata:
      annotations:
        dapr.io/app-id: consumer-app
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
        dapr.io/log-level: "debug"
      labels:
        app: consumer-app
    spec:
      containers:
      - image: salaboy/consumer-app:0.3.0
        name: consumer-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: consumer-app
