apiVersion: v1
kind: Service
metadata:
  labels:
    app: otel
  name: otel
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 4318
    targetPort: 4318
    nodePort: 31003
  selector:
    app: otel

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: otel
  name: otel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel
  template:
    metadata:
      labels:
        app: otel
    spec:
      containers:
      - image: otel/opentelemetry-collector:0.110.0
        name: otel
        imagePullPolicy: Always
        command:
          - "/otelcol"
          - "--config=/conf/otel-collector-config.yaml"
        volumeMounts:
          - name: otel-collector-config-vol
            mountPath: /conf
        ports:
        - containerPort: 4318
          name: http
      volumes:
        - configMap:
            name: otel-collector-conf
            items:
              - key: otel-collector-config
                path: otel-collector-config.yaml
          name: otel-collector-config-vol    