apiVersion: v1
kind: Service
metadata:
  labels:
    app: producer-app
  name: producer-app
spec:
  type: NodePort
  ports:
  - name: "consumer-app"
    port: 8080
    targetPort: 8080
    nodePort: 31000
  selector:
    app: producer-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: producer-app
  name: producer-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-app
  template:
    metadata:
      annotations:  
        dapr.io/app-id: producer-app-dapr
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
        dapr.io/log-level: "debug"
        dapr.io/config: "my-config"
      labels:
        app: producer-app
    spec:
      containers:
      - image: salaboy/producer-app-elastic:amd64
        name: producer-app
        imagePullPolicy: Always
        env: 
        - name: DAPR_CLIENT_HTTPENDPOINT
          value: http://localhost:3500
        ports:
        - containerPort: 8080
          name: producer-app