apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: resiliency-policy
scopes:
  - consumer-app
  - producer-app
spec:
  policies:
    retries:
      retryForever:
        policy: constant
        maxInterval: 5s
        maxRetries: -1 

    circuitBreakers:
      simpleCB:
        maxRequests: 1
        timeout: 5s 
        trip: consecutiveFailures >= 5

  targets:
    apps:
      consumer-app:
        retry: retryForever
        circuitBreaker: simpleCB